name: Auto Review and Merge Pull Requests

on:
  pull_request:
    types:
      - opened

jobs:
  review-and-merge:
    name: Review, Approve, and Merge
    runs-on: ubuntu-latest

    steps:
    - name: Review and Approve Pull Request
      uses: kentaro-m/auto-approve-action@v2.1.0

    - name: Merge Pull Request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh pr merge ${{ github.event.pull_request.html_url }} --merge